### ISSUE TITLE
Error on Raspberry Pi OS - _bluetooth.error: (9, 'Bad file descriptor')

### ISSUE THREAD

**Issue by Andperro** [bluez/bluez#133]
Hi,

I'm facing a problem with Bluez library when running Raspberry Pi OS on a Raspberry Pi Zero W.
I'm running a fresh install of the latest image version with release date in March 4th 2021.

I've tried two different approaches to scan iBeacons and the same error happened, thus, I think that it myth be related to the Bluez itself. 

**Code tested**

https://github.com/citruz/beacontools

https://github.com/bowdentheo/BLE-Beacon-Scanner

Below, the error that I'm getting:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/pi/.local/lib/python3.7/site-packages/beacontools/scanner.py", line 144, in run
    self.socket = self.backend.open_dev(self.bt_device_id)
  File "/home/pi/.local/lib/python3.7/site-packages/beacontools/backend/linux.py", line 13, in open_dev
    socket.setsockopt(bluez.SOL_HCI, bluez.HCI_FILTER, filtr)
_bluetooth.error: (9, 'Bad file descriptor')
```

Please, let me know if I can provide further information.

Thank you all in advance

**Comment by Vudentz** [comment]
@Andperro you should probably go back to those projects since that is using HCI_RAW it probably out of BlueZ scope, except if you thing this is a kernel bug, you will need to check if your process has permission to open raw sockets which is probably the reason why this is happening. If you want to do the proper way then use BlueZ StartDiscovery:

https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/adapter-api.txt#n12

You can have filters with:

https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/adapter-api.txt#n49

Or alternatively can use offload to the controller using AdvertisingMonitor:

https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/advertisement-monitor-api.txt
