### ISSUE TITLE
Can't see registered player when introspecting

### ISSUE THREAD

**Issue by lapinozz** [bluez/bluez#23]
So I've registered a player using the python example
It seems to register fine as it doesn't error anymore and the log in "/var/log/syslog" says it's registered

But when I introspect with `gdbus introspect  --system --dest org.bluez --object-path /org --recurse` I don't see it
Am I missing something?

The reason I want to register a player is for my headphone which connects but doesn't have a player so the volume key have no effects.
I checked the code and it seems like it's checking if it has a player if it does it updates the Volume property.

Thanks!

**Comment by Vudentz** [comment]
Registered player would be on its connection id not under org.bluez if that is what you expect. The headset is still expected to send button presses for volume up and down, or you saying that has no effect in your system?

**Comment by lapinozz** [comment]
I'm not sure what you mean by "its connection id"?

Regardless, I do see that the volume get sent and process
![image](https://user-images.githubusercontent.com/7329064/86278884-14231f00-bba7-11ea-93bf-f14fc348a274.png)

But I would like to receive that update programmatically. 
It doesn't seem to change the system sound level on my ubuntu machine

**Comment by Vudentz** [comment]
That is for the headset to notify its volume changes, changes to that would be notified to the MediaTransport directly:

https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/media-api.txt#n651

Since it can only be changed by the application that acquired the transport you can change it directly, PulseAudio exposes it own volume control so you can access the volume via the audio card created for your headset, perhaps you are saying that doesn't working for some reason.

**Comment by Vudentz** [comment]
The following patch should have fixed the volume:

https://git.kernel.org/pub/scm/bluetooth/bluez.git/commit/?id=df7d3fa5002373f7f955219defc7d0bc794a5a6c
