### ISSUE TITLE
Bluetooth and dual-booting between Linux and Windows

### ISSUE THREAD

**Issue by pguerin3** [bluez/bluez#266]
I own bluetooth earbuds, and bluetooth headphones.
Both worked fine in Windows, and I could switch between devices and connect without a problem.

However, now I dual-boot between Windows, and Fedora 35.
I can use the earbuds on Fedora 35, but when I try the headphones they no longer connect.
I can use the headphones in Windows, but the earbuds won't connect.

I was reading in another forum that there is a problem with connecting bluetooth devices when dual-booting.

Using bluetoothctl in Fedora, there isn't an obvious sequence of commands to rectify the situation.
So I'm wondering if there is a procedure, using bluetoothctl, or other tools, that I can use to allow me to use either bluetooth device in Fedora?

**Comment by Vudentz** [comment]
Im afraid this is not supported since the windows and the linux don't share any information such as link-keys, etc, so once you boot another OS it has no idea that it had been paired, or in case it was previously paired that its link-keys are no longer valid, so all you can do is to remove the device and attempt to do a new pairing.

**Comment by pguerin3** [comment]
No problem - I have worked out that the commands to get the device to work again, and they are as follows:
```
remove <device>
scan on
```
Once the device has been scanned, then do the following:
```
scan off
pair <device>
connect <device>
```
Your device should now work.
