### ISSUE TITLE
[Bluez 5.64]  Amazon 2nd GEN Fire TV remote input not working after updating to bluez 5.64

### ISSUE THREAD

**Issue by pretoriano80** [bluez/bluez#326]
**Description:** After updating to Bluez 5.64 my  Amazon 2nd GEN Fire TV remote is pairing correctly but no input is detected.Downgradin to 5.63 without any other modification ,addresses the issue and the remote works again.

**OS:** LibreELEC 
**Device:** RaspberryPi 4**

**Testing results:** After testing the 5.63 --> 5.64 commits one by one i've found the issue is caused by https://github.com/bluez/bluez/commit/411d63ec33a23bdbad73276067d02f9981229d0b and reverting only that commit on my local build fixed the issue.

You can also find more details and **debug logs** here --> https://github.com/LibreELEC/LibreELEC.tv/issues/6348

**Comment by Vudentz** [comment]
@pretoriano80 please enable bluetoothd logs, Id like to see the GATT database layout since one of the causes of this problem could be the device putting descriptors before the characteristic value which is not allowed by the spec, also note that https://github.com/bluez/bluez/commit/411d63ec33a23bdbad73276067d02f9981229d0b is actually required for server notification to work properly so reverting that would probably break other peripheral role.

**Comment by Vudentz** [comment]
@pretoriano80 please give it a try with the patch above.

**Comment by pretoriano80** [comment]
@Vudentz patch tested and i can confirm that it addresses this issue.Thank you for the extremely fast fix.
