### ISSUE TITLE
Failed to set Privacy: Rejected (0x0b)

### ISSUE THREAD

**Issue by montedison** [bluez/bluez#385]
I installed raspbian armhf and arm64 bullseye and buster on a raspberry pi 3 model B
As default the system gives this error and doesn't pair with my phone.
Tried the daemon version 5.50 and 5.55 (and all others available with debsnap!!)
And i see it's broken from months....it's embarassing! I can use my raspberry only because i had a lucky image from 3 years ago!!
It should be the stable version and it doesn't fucking work from months!
HOW TO REPRODUCE THE ERROR? JUST INSTALL A PLAIN "STABLE" RASPBIAN IMAGE ON A RASPBERRY PI 3

**Comment by Vudentz** [comment]
And you are complaining here and not on distro itself for what reason? These are not latest upstream version, and this sort of tone is very rude to say the least, if you want someone to help please learn how to communicate with open source community, we don't work as help desk/customer service that tolerate such language because they are paid to do it.
