### ISSUE TITLE
Bluetooth: SMP security requested but not available And Set Secure Connection failed

### ISSUE THREAD

**Issue by LIUpeirun** [bluez/bluez#581]
Hello,I recently encountered some issues porting Bluez to Linux system.
My Linux kernel version is 4.4.19 and bluez version is 5.60
When I used the IOS system phone to connect to the Bluetooth on my board, this exception occurred.
```
Bluetooth: SMP security requested but not available
bluetoothd[600]: src/device.c:gatt_debug() (chan 0x172a3b0) Retrying operation 0x17368d0
Bluetooth: SMP security requested but not available
bluetoothd[600]: src/device.c:gatt_debug() (chan 0x172a3b0) Retrying operation 0x17368d0
```
It is worth mentioning that when I use an Android phone, such an exception does not occur.When I started Bluetooth, I observed that such an error occurred.
`bluetoothd[2526]: Failed to set privacy: Rejected (0x0b)`
For this error, I tried using btmgmt sc off to close the secure connection and modify privacy=off in main.conf,But they will still face the same mistake.
```
[rootaanyka~]$ btmgmt bredr off
Set BR/EDR for hci failed with status 0x0b (Rejected)
[rootaanyka~]$ btmgmt le off
hcio Set Low Energy complete, settings: powered br/edr
[rootaanyka -]$ btmgmt le oepn
hci0 Set Low Energy complete, settings: powered br/edr
[root@anyka~]$ btmgmt bredr off
Set BR/EDR for hci0 failed with status 0x0b (Rejected)
[rootanyka-]$ btmgmt bredr open
Set BR/EDR for hci failed with status 0xb(Rejected)
[rootaanyka -]$ btmgmt sc open
Set Secure Connections for hcio failed with status 0x0b (Rejected)
[root@anyka ~]$ btmgmt sc off
Set Secure Connections for hci0 failed with status 0x0b (Rejected)
[rootaanyka ~]$ btmgmt privacy open
Set Privacy for hci0 failed with status 0xb (Rejected)
[rootaanyka~]$ btmgmt privacy off
Set Privacy hci0 failed with status 0xOb (Rejected)
```
This is the information about Bluetooth printed by the kernel
```
Bluetooth: Core ver 2.21
Bluetooth: HCI device and connection manager initialized
Bluetooth: HCI socket layer initialized
Bluetooth: L2CAP socket layer initialized
Bluetooth: HCI UART driver ver 2.3
Bluetooth: HCI UART protocol H4 registered
Bluetooth: HCI UART protocol Three-wire (H5) registered
```
I don't know how to solve this problem, so I would like to ask for your advice. Thank you very much.

**Comment by LIUpeirun** [comment]
I feel that this should be related to a certain configuration in the kernel, but I don't know how to solve it or which configuration is related. This is my personal guess

**Comment by Aye-zang** [comment]
you need let the power off first. 
use` btmgmt power off` then ` btmgmt privacy on`

**Comment by Altair-Bueno** [comment]
> you need let the power off first.
> use btmgmt power off then  btmgmt privacy on

Let me elaborate on your response. Precisely because I've spent half a work week debugging our BLE communications on our fleet of embedded devices, and I'll like to save someone in the future some pain.

---

Apparently, some Bluetooth antennas do not support hot configuring some settings. For example, our embedded boards do not support enabling/disabling pairing while the antenna is powered on. So, if your application does something like this:

```py
adapter.set_powered(true)
adapter.set_pairing(true)
register_agent()
# ...
```

You are cooked. The right way to do it (apparently) is to:

1. Turn off the antenna
2. Edit whatever settings you need to do. In my case, it was privacy the setting giving us headaches, but I imagine that privacy is also one of them.
3. Turn the antenna back on

```py
# Make sure it's powered down
adapter.set_powered(false)
adapter.set_pairing(true)
register_agent()

# And now you turn it on
adapter.set_powered(true)
```

You would expect Bluez to rise a D-Bus error when attempting to modify an antenna setting while is powered on... Or restarting the antenna for you... But for whatever reason it doesn't. And you are stuck with a malfunctioning antenna with no idea why it isn't working. Probably because the driver lies and tells Bluez the action was performed successfully when, in reality, the action wasn't performed at all.

And also, as far as I can tell, none of the examples/tests/docs within Bluez explain that this might happen. It may be due to it being "common knowledge" or something like that, who knows. I definitely didn't.
