### ISSUE TITLE
set position about A2DP

### ISSUE THREAD

**Issue by luoyuyi111** [bluez/bluez#653]
Hi, I have a question:

Why does function set_position in file "profiles/audio/media.c" send AVRCP_EVENT_STATUS_CHANGED event when I want to set position?

I think we should send AVRCP_EVENT_TRACK_CHANGED  event

**Comment by Vudentz** [comment]
@luoyuyi111 it is there as a comment:

`/* Send a status change to force resync the position */`

We could alternatively send AVRCP_EVENT_PLAYBACK_POS_CHANGED, but afaik that is not mandatory to be supported nor we set set as supported either, anyway we force a forward/backward-seek depending if the position went forward or backwards, imo AVRCP_EVENT_TRACK_CHANGED makes no send since this operation is not meant to change tracks.
