### ISSUE TITLE
Regression: Hitting ctrl+u in bluetoothctl erases the prompt

### ISSUE THREAD

**Issue by NetSysFire** [bluez/bluez#965]
Steps to reproduce:

1. Fire up bluetoothctl.
2. Type anything, even a single letter works here.
3. Press Ctrl+u, which is a standard readline keybind to erase the current text behind the cursor.
4. The prompt gets erased, too. In order to bring it back you have to hit enter.

Expected behavior:

The prompt does not get erased. This is a regression as it has worked great in the past but it has changed some months ago. Unfortunately I do not know in which version exactly.

This is a minor bug. It is a bit annoying but does not critically impair any functionality.

Environment:

Version `5.78-1` on Arch Linux. I got two other people on the same distro to reproduce this, too.

**Comment by hardfalcon** [comment]
I can confirm that with `bluetoothctl` from `bluez-utils 5.78-1` on Archlinux x86_64, at least the following readline keyboard shortcuts don't work as intended:
- `Ctrl`+`U` (erases everything, including the prompt)
- `Ctrl`+`W` (when used on the first word, both that first word and the prompt itself are erased)
- `Ctrl`+`A` (more cursor to the beginning of the prompt string instead of one character after the end of the prompt string)
- `Ctrl`+`E` after `Ctrl`+`A` has been used (inherits an offset to the left that is equal to the length of the prompt string)

This is caused by commit d8fc0dd5942e6e7b95833ee47fc4a8821c0c3421, and reverting that commit solves the issue for me.

I don't have any experience using readline as a developer, so take this with a grain of salt. I *think* the problem with that commit is that it envelops the *whole* prompt string in readline's `RL_PROMPT_START_IGNORE` (=`\001`) and `RL_PROMPT_END_IGNORE` (=`\002`) special characters, instead of only the non-printable escape sequences for color formatting like it is supposed to be done [according to readline's documentation](https://tiswww.cwru.edu/php/chet/readline/readline.html#index-rl_005fexpand_005fprompt).

**Comment by NetSysFire** [comment]
CC @Vudentz then.

**Comment by Vudentz** [comment]
@NetSysFire yeah, well if we can't use RL_PROMPT_START_IGNORE we can't use colors either, at least not embedded into the prompt string itself so we may need to the color as a separate parameter in order to properly encode the ignore symbols.

**Comment by Vudentz** [comment]
@hardfalcon @NetSysFire can you guys test with the changes above?

**Comment by NetSysFire** [comment]
Can confirm that the commit fixes that. Thank you!

**Comment by hardfalcon** [comment]
Sorry for the delay. I've finally gotten around to test this, and I can confirm that commit https://github.com/bluez/bluez/commit/ee6f3a837e325184ea1009b94dee20411480844e applied on top of release [5.78](https://github.com/bluez/bluez/releases/tag/5.78) does indeed solve the issue for me. Thanks a lot for the quick fix and your great work overall, @Vudentz! :)
